apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signatures
  annotations:
    policies.kyverno.io/title: Verify Image Signatures
    policies.kyverno.io/category: Supply Chain Security
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  background: false
  failurePolicy: Fail
  rules:
    - name: verify-github-keyless
      match:
        any:
          - resources:
              kinds: [Pod]
      exclude:
        any:
          - resources:
              namespaces: [kube-system, kyverno, gmp-system, gke-managed-system, external-secrets, observability]
      verifyImages:
        - imageReferences:
            - "us-central1-docker.pkg.dev/project-90390b2c-d762-4668-939/reference/reference-app*"
          required: false
          mutateDigest: false
          verifyDigest: false
          attestors:
            - entries:
                - keyless:
                    subject: "https://github.com/sebrakoczy/terraform-gke/.github/workflows/ci.yml@refs/heads/main"
                    issuer: "https://token.actions.githubusercontent.com"
                    rekor:
                      url: https://rekor.sigstore.dev
